/// Flutter icons TelecomAppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TelecomAppIcons
///      fonts:
///       - asset: fonts/TelecomAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TelecomAppIcons {
  TelecomAppIcons._();

  static const _kFontFam = 'TelecomAppIcons';
  static const String? _kFontPkg = null;

  static const IconData vector__5_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__4_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
